baseurl: "https://chrisdoherty.io/"
title: Chris Doherty
theme: hyde

params:
  author: Chris Doherty
  description: |
    I'm a Software Engineer passionate about all things technical.
  themeColor: theme-base-09

menu:
  main:
    - name: Posts
      url: /posts
      weight: 2
    - name: "Github"
      url: https://github.com/chrisdoherty4
    - name: LinkedIn
      url: https://linkedin.com/in/chrisdoherty4
