baseurl: "https://chrisdoherty.io/"
title: Chris Doherty
theme: ghostwriter
languageCode: en-us
copyright: Chris Doherty
# googleAnalytics: XXX
# disqusShortname: XXX
pygmentsUseClasses: true
pygmentsCodefences: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: Chris Doherty
  profile: "https://github.com/chrisdoherty4"

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  intro: true
  headline: Chris Doherty
  description: software engineer passionate about all things technical
  github: "https://github.com/chrisdoherty4"
  gitlab: "https://gitlab.com/chrisdoherty4"
  linkedin: "https://linkedin.com/in/chrisdoherty4/"
  twitter: ""
  stackoverflow: ""
  facebook: ""
  email: chris@chrisdoherty.io
  opengraph: true
  shareTwitter: false
  shareFacebook: false
  shareGooglePlus: false
  shareLinkedIn: false
  dateFormat: "Mon, Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: Blog
      url: /
      weight: 1
    - name: Projects
      url: /project/
      weight: 2
    - name: Contact
      url: /page/contact/
      weight: 3
    - name: About
      url: /page/about/
      weight: 4